/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'pending' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'interviewing' : null } |
  { 'offered' : null };
export interface GeoLocation {
  'region' : string,
  'country' : string,
  'city' : string,
  'radiusKm' : [] | [bigint],
}
export interface JobApplication {
  'status' : ApplicationStatus,
  'owner' : Principal,
  'submissionChecklist' : Array<string>,
  'customCoverLetter' : [] | [string],
  'jobId' : string,
  'dateApplied' : Time,
  'resumeId' : string,
  'applicationSource' : [] | [string],
}
export interface JobPosting {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'company' : string,
  'applicationUrl' : [] | [string],
  'datePosted' : Time,
  'requirements' : [] | [string],
  'location' : string,
  'contactDetails' : [] | [string],
}
export interface MatchScore {
  'matchedKeywords' : Array<string>,
  'jobId' : string,
  'score' : bigint,
}
export interface ResumeProfile {
  'resumeText' : string,
  'coverLetterText' : string,
  'location' : GeoLocation,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobPosting' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateJobMatch' : ActorMethod<[string], [] | [MatchScore]>,
  'createApplication' : ActorMethod<[string], string>,
  'deleteJobPosting' : ActorMethod<[string], undefined>,
  'getAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobApplication' : ActorMethod<[string], [] | [JobApplication]>,
  'getJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getJobPosting' : ActorMethod<[string], [] | [JobPosting]>,
  'getJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getResumeProfile' : ActorMethod<[], [] | [ResumeProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveResumeProfile' : ActorMethod<[string, string, GeoLocation], undefined>,
  'updateApplicationCoverLetter' : ActorMethod<[string, string], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];