/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchScore = IDL.Record({
  'matchedKeywords' : IDL.Vec(IDL.Text),
  'jobId' : IDL.Text,
  'score' : IDL.Nat,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'interviewing' : IDL.Null,
  'offered' : IDL.Null,
});
export const Time = IDL.Int;
export const JobApplication = IDL.Record({
  'status' : ApplicationStatus,
  'owner' : IDL.Principal,
  'submissionChecklist' : IDL.Vec(IDL.Text),
  'customCoverLetter' : IDL.Opt(IDL.Text),
  'jobId' : IDL.Text,
  'dateApplied' : Time,
  'resumeId' : IDL.Text,
  'applicationSource' : IDL.Opt(IDL.Text),
});
export const JobPosting = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'applicationUrl' : IDL.Opt(IDL.Text),
  'datePosted' : Time,
  'requirements' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'contactDetails' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const GeoLocation = IDL.Record({
  'region' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'radiusKm' : IDL.Opt(IDL.Nat),
});
export const ResumeProfile = IDL.Record({
  'resumeText' : IDL.Text,
  'coverLetterText' : IDL.Text,
  'location' : GeoLocation,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobPosting' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateJobMatch' : IDL.Func([IDL.Text], [IDL.Opt(MatchScore)], ['query']),
  'createApplication' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteJobPosting' : IDL.Func([IDL.Text], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(JobApplication)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getResumeProfile' : IDL.Func([], [IDL.Opt(ResumeProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveResumeProfile' : IDL.Func([IDL.Text, IDL.Text, GeoLocation], [], []),
  'updateApplicationCoverLetter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchScore = IDL.Record({
    'matchedKeywords' : IDL.Vec(IDL.Text),
    'jobId' : IDL.Text,
    'score' : IDL.Nat,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'interviewing' : IDL.Null,
    'offered' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobApplication = IDL.Record({
    'status' : ApplicationStatus,
    'owner' : IDL.Principal,
    'submissionChecklist' : IDL.Vec(IDL.Text),
    'customCoverLetter' : IDL.Opt(IDL.Text),
    'jobId' : IDL.Text,
    'dateApplied' : Time,
    'resumeId' : IDL.Text,
    'applicationSource' : IDL.Opt(IDL.Text),
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'applicationUrl' : IDL.Opt(IDL.Text),
    'datePosted' : Time,
    'requirements' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'contactDetails' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const GeoLocation = IDL.Record({
    'region' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'radiusKm' : IDL.Opt(IDL.Nat),
  });
  const ResumeProfile = IDL.Record({
    'resumeText' : IDL.Text,
    'coverLetterText' : IDL.Text,
    'location' : GeoLocation,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobPosting' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateJobMatch' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MatchScore)],
        ['query'],
      ),
    'createApplication' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteJobPosting' : IDL.Func([IDL.Text], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(JobApplication)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getResumeProfile' : IDL.Func([], [IDL.Opt(ResumeProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveResumeProfile' : IDL.Func([IDL.Text, IDL.Text, GeoLocation], [], []),
    'updateApplicationCoverLetter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };